In [1]:
# Import dependencies
import pandas as pd
# from pyxlsb import open_workbook

# from config import postgres_password
# from sqlalchemy import create_engine

# Extract Data Into DataFrames For Temperature

### NASA Climate Dataset

In [2]:
# Import data file
nasa_file = "raw_data/nasa_land_ocean_temp.csv"

nasa_temp = pd.read_csv(nasa_file)
display(nasa_temp.head(5))
display(nasa_temp.tail(5))

   Year  No_Smoothing  Lowess(5)
0  1880         -0.16      -0.08
1  1881         -0.07      -0.12
2  1882         -0.10      -0.16
3  1883         -0.16      -0.19
4  1884         -0.27      -0.23

     Year  No_Smoothing  Lowess(5)
136  2016          1.02       0.88
137  2017          0.93       0.91
138  2018          0.85       0.95
139  2019          0.98       0.98
140  2020          1.02       1.01

### Kaggle Temperature Change Dataset

In [3]:
# Import data file
all_temp_file = "raw_data/Environment_Temperature_change_E_All_Data_NOFLAG.csv"

all_temp = pd.read_csv(all_temp_file, encoding="ISO-8859-1")
display(all_temp.head(5))
display(all_temp.tail(5))

,Area Code,Area,Months Code,Months,Element Code,Element,Unit,Y1961,Y1962,Y1963,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,2,Afghanistan,7001,January,7271,Temperature change,°C,0.777,0.062,2.744,...,3.601,1.179,-0.583,1.233,1.755,1.943,3.416,1.201,1.996,2.951
1,2,Afghanistan,7001,January,6078,Standard Deviation,°C,1.950,1.950,1.950,...,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950
2,2,Afghanistan,7002,February,7271,Temperature change,°C,-1.743,2.465,3.919,...,1.212,0.321,-3.201,1.494,-3.187,2.699,2.251,-0.323,2.705,0.086
3,2,Afghanistan,7002,February,6078,Standard Deviation,°C,2.597,2.597,2.597,...,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597
4,2,Afghanistan,7003,March,7271,Temperature change,°C,0.516,1.336,0.403,...,3.390,0.748,-0.527,2.246,-0.076,-0.497,2.296,0.834,4.418,0.234

,Area Code,Area,Months Code,Months,Element Code,Element,Unit,Y1961,Y1962,Y1963,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
9651,5873,OECD,7018,JunJulAug,6078,Standard Deviation,°C,0.247,0.247,0.247,...,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247
9652,5873,OECD,7019,SepOctNov,7271,Temperature change,°C,0.036,0.461,0.665,...,0.958,1.106,0.885,1.041,0.999,1.670,1.535,1.194,0.581,1.233
9653,5873,OECD,7019,SepOctNov,6078,Standard Deviation,°C,0.378,0.378,0.378,...,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378
9654,5873,OECD,7020,Meteorological year,7271,Temperature change,°C,0.165,-0.009,0.134,...,1.246,0.805,1.274,0.991,0.811,1.282,1.850,1.349,1.088,1.297
9655,5873,OECD,7020,Meteorological year,6078,Standard Deviation,°C,0.260,0.260,0.260,...,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260

# Transform Data for Energy and Emission

### NASA Climate Dataset

In [4]:
# Extract the wanted columns
list(nasa_temp.columns)

['Year', 'No_Smoothing', 'Lowess(5)']

In [5]:
# Lowess smooths the data, no_smoothing 
nasa_temp_df = nasa_temp[["Year", "No_Smoothing", "Lowess(5)"]]
nasa_temp_df.head()

   Year  No_Smoothing  Lowess(5)
0  1880         -0.16      -0.08
1  1881         -0.07      -0.12
2  1882         -0.10      -0.16
3  1883         -0.16      -0.19
4  1884         -0.27      -0.23

In [6]:
# Extract year from 1965 to the most recent
nasa_temp_new_df = nasa_temp_df[nasa_temp_df["Year"]>1964]
nasa_temp_new_df.head()

    Year  No_Smoothing  Lowess(5)
85  1965         -0.11      -0.05
86  1966         -0.06      -0.06
87  1967         -0.02      -0.05
88  1968         -0.08      -0.03
89  1969          0.05      -0.02

In [7]:
nasa_temp_new_df.reset_index(drop=True).head()

   Year  No_Smoothing  Lowess(5)
0  1965         -0.11      -0.05
1  1966         -0.06      -0.06
2  1967         -0.02      -0.05
3  1968         -0.08      -0.03
4  1969          0.05      -0.02

### Kaggle Temperature Change Dataset

In [8]:
# Import kaggle data
kaggle_temp = "raw_data/Environment_Temperature_change_E_All_Data_NOFLAG.csv"
kaggle_temp = pd.read_csv(kaggle_temp, encoding="ISO-8859-1")
kaggle_temp.head(50)

,Area Code,Area,Months Code,Months,Element Code,Element,Unit,Y1961,Y1962,Y1963,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,2,Afghanistan,7001,January,7271,Temperature change,°C,0.777,0.062,2.744,...,3.601,1.179,-0.583,1.233,1.755,1.943,3.416,1.201,1.996,2.951
1,2,Afghanistan,7001,January,6078,Standard Deviation,°C,1.950,1.950,1.950,...,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950
2,2,Afghanistan,7002,February,7271,Temperature change,°C,-1.743,2.465,3.919,...,1.212,0.321,-3.201,1.494,-3.187,2.699,2.251,-0.323,2.705,0.086
3,2,Afghanistan,7002,February,6078,Standard Deviation,°C,2.597,2.597,2.597,...,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597
4,2,Afghanistan,7003,March,7271,Temperature change,°C,0.516,1.336,0.403,...,3.390,0.748,-0.527,2.246,-0.076,-0.497,2.296,0.834,4.418,0.234
5,2,Afghanistan,7003,March,6078,Standard Deviation,°C,1.512,1.512,1.512,...,1.512,1.512,1.512,1.512,1.512,1.512,1.512,1.512,1.512,1.512
6,2,Afghanistan,7004,April,7271,Temperature change,°C,-1.709,0.117,0.919,...,2.591,1.712,1.417,-0.052,0.585,1.589,0.980,1.252,1.442,0.899
7,2,Afghanistan,7004,April,6078,Standard Deviation,°C,1.406,1.406,1.406,...,1.406,1.406,1.406,1.406,1.406,1.406,1.406,1.406,1.406,1.406
8,2,Afghanistan,7005,May,7271,Temperature change,°C,1.412,-0.092,-0.690,...,1.419,3.643,0.909,1.201,0.959,1.862,3.246,3.280,0.855,0.647
9,2,Afghanistan,7005,May,6078,Standard Deviation,°C,1.230,1.230,1.230,...,1.230,1.230,1.230,1.230,1.230,1.230,1.230,1.230,1.230,1.230
10,2,Afghanistan,7006,June,7271,Temperature change,°C,-0.058,-1.061,1.164,...,0.594,2.450,0.305,1.924,1.492,1.289,1.586,2.002,1.786,-0.289
11,2,Afghanistan,7006,June,6078,Standard Deviation,°C,0.930,0.930,0.930,...,0.930,0.930,0.930,0.930,0.930,0.930,0.930,0.930,0.930,0.930
12,2,Afghanistan,7007,July,7271,Temperature change,°C,0.884,0.292,0.348,...,0.494,0.532,0.973,1.126,0.671,1.092,1.079,0.901,1.815,1.885
13,2,Afghanistan,7007,July,6078,Standard Deviation,°C,0.585,0.585,0.585,...,0.585,0.585,0.585,0.585,0.585,0.585,0.585,0.585,0.585,0.585
14,2,Afghanistan,7008,August,7271,Temperature change,°C,0.391,-0.220,0.094,...,0.587,1.930,1.356,0.886,0.706,0.589,0.311,0.102,0.982,0.773
15,2,Afghanistan,7008,August,6078,Standard Deviation,°C,0.773,0.773,0.773,...,0.773,0.773,0.773,0.773,0.773,0.773,0.773,0.773,0.773,0.773
16,2,Afghanistan,7009,September,7271,Temperature change,°C,1.445,-1.797,0.163,...,0.030,1.408,0.495,2.586,2.268,0.172,3.016,0.930,1.063,2.004
17,2,Afghanistan,7009,September,6078,Standard Deviation,°C,0.832,0.832,0.832,...,0.832,0.832,0.832,0.832,0.832,0.832,0.832,0.832,0.832,0.832
18,2,Afghanistan,7010,October,7271,Temperature change,°C,-1.102,-0.968,1.654,...,2.927,1.339,0.827,1.691,1.134,1.894,0.792,2.092,-0.103,1.264
19,2,Afghanistan,7010,October,6078,Standard Deviation,°C,1.310,1.310,1.310,...,1.310,1.310,1.310,1.310,1.310,1.310,1.310,1.310,1.310,1.310
20,2,Afghanistan,7011,November,7271,Temperature change,°C,-0.540,-2.171,0.584,...,0.975,1.000,1.042,0.975,-0.403,0.512,-1.345,2.089,0.882,-1.051
21,2,Afghanistan,7011,November,6078,Standard Deviation,°C,1.391,1.391,1.391,...,1.391,1.391,1.391,1.391,1.391,1.391,1.391,1.391,1.391,1.391
22,2,Afghanistan,7012,December,7271,Temperature change,°C,0.600,-0.721,-0.603,...,-0.154,-1.789,-0.467,-0.216,0.005,0.048,3.429,0.441,1.311,1.426
23,2,Afghanistan,7012,December,6078,Standard Deviation,°C,1.516,1.516,1.516,...,1.516,1.516,1.516,1.516,1.516,1.516,1.516,1.516,1.516,1.516
24,2,Afghanistan,7016,DecJanFeb,7271,Temperature change,°C,-0.731,1.042,1.981,...,1.921,0.449,-1.858,0.753,-0.549,1.549,1.905,1.436,1.714,1.449
25,2,Afghanistan,7016,DecJanFeb,6078,Standard Deviation,°C,1.335,1.335,1.335,...,1.335,1.335,1.335,1.335,1.335,1.335,1.335,1.335,1.335,1.335
26,2,Afghanistan,7017,MarAprMay,7271,Temperature change,°C,0.073,0.454,0.211,...,2.467,2.034,0.600,1.132,0.489,0.985,2.174,1.789,2.238,0.593
27,2,Afghanistan,7017,MarAprMay,6078,Standard Deviation,°C,0.932,0.932,0.932,...,0.932,0.932,0.932,0.932,0.932,0.932,0.932,0.932,0.932,0.932
28,2,Afghanistan,7018,JunJulAug,7271,Temperature change,°C,0.406,-0.330,0.535,...,0.558,1.637,0.878,1.312,0.956,0.990,0.992,1.002,1.528,0.790
29,2,Afghanistan,7018,JunJulAug,6078,Standard Deviation,°C,0.562,0.562,0.562,...,0.562,0.562,0.562,0.562,0.562,0.562,0.562,0.562,0.562,0.562
30,2,Afghanistan,7019,SepOctNov,7271,Temperature change,°C,-0.066,-1.645,0.800,...,1.311,1.249,0.788,1.751,1.000,0.859,0.821,1.704,0.614,0.739
31,2,Afghanistan,7019,SepOctNov,6078,Standard Deviation,°C,0.783,0.783,0.783,...,0.783,0.783,0.783,0.783,0.783,0.783,0.783,0.783,0.783,0.783
32,2,Afghanistan,7020,Meteorological year,7271,Temperature change,°C,-0.080,-0.120,0.882,...,1.564,1.342,0.102,1.237,0.474,1.096,1.473,1.483,1.524,0.893
33,2,Afghanistan,7020,Meteorological year,6078,Standard Deviation,°C,0.548,0.548,0.548,...,0.548,0.548,0.548,0.548,0.548,0.548,0.548,0.548,0.548,0.548
34,3,Albania,7001,January,7271,Temperature change,°C,0.180,1.414,-1.783,...,1.137,0.812,-1.004,1.760,3.583,1.083,1.530,-2.470,2.304,-0.816
35,3,Albania,7001,January,6078,Standard Deviation,°C,1.472,1.472,1.472,...,1.472,1.472,1.472,1.472,1.472,1.472,1.472,1.472,1.472,1.472
36,3,Albania,7002,February,7271,Temperature change,°C,-0.625,-2.125,-0.621,...,0.879,0.554,-2.714,1.219,3.502,0.378,4.611,2.622,0.765,1.563
37,3,Albania,7002,February,6078,Standard Deviation,°C,1.939,1.939,1.939,...,1.939,1.939,1.939,1.939,1.939,1.939,1.939,1.939,1.939,1.939
38,3,Albania,7003,March,7271,Temperature change,°C,0.995,-0.782,-1.487,...,1.079,1.521,2.081,1.420,2.363,0.777,1.670,3.419,1.768,3.119
39,3,Albania,7003,March,6078,Standard Deviation,°C,1.356,1.356,1.356,...,1.356,1.356,1.356,1.356,1.356,1.356,1.356,1.356,1.356,1.356
40,3,Albania,7004,April,7271,Temperature change,°C,2.412,0.518,0.601,...,1.804,1.350,1.320,2.509,1.076,0.607,3.554,0.938,4.878,1.866
41,3,Albania,7004,April,6078,Standard Deviation,°C,1.181,1.181,1.181,...,1.181,1.181,1.181,1.181,1.181,1.181,1.181,1.181,1.181,1.181
42,3,Albania,7005,May,7271,Temperature change,°C,-0.515,0.568,-0.074,...,0.938,0.687,0.916,2.107,0.079,2.341,0.141,1.424,3.424,-0.822
43,3,Albania,7005,May,6078,Standard Deviation,°C,1.173,1.173,1.173,...,1.173,1.173,1.173,1.173,1.173,1.173,1.173,1.173,1.173,1.173
44,3,Albania,7006,June,7271,Temperature change,°C,0.176,-0.772,0.449,...,0.847,1.384,3.084,0.896,1.052,1.278,1.974,2.879,1.709,3.474
45,3,Albania,7006,June,6078,Standard Deviation,°C,0.870,0.870,0.870,...,0.870,0.870,0.870,0.870,0.870,0.870,0.870,0.870,0.870,0.870
46,3,Albania,7007,July,7271,Temperature change,°C,-0.338,0.355,1.178,...,1.676,1.228,3.824,1.452,0.353,3.828,2.373,2.783,1.538,1.873
47,3,Albania,7007,July,6078,Standard Deviation,°C,0.715,0.715,0.715,...,0.715,0.715,0.715,0.715,0.715,0.715,0.715,0.715,0.715,0.715
48,3,Albania,7008,August,7271,Temperature change,°C,-0.163,2.025,1.229,...,2.518,2.444,3.130,2.822,1.440,3.174,1.414,3.522,2.704,3.336
49,3,Albania,7008,August,6078,Standard Deviation,°C,1.288,1.288,1.288,...,1.288,1.288,1.288,1.288,1.288,1.288,1.288,1.288,1.288,1.288

In [40]:
cleaned_temp = kaggle_temp.drop(columns=['Area Code', 'Months Code', 'Element Code', 'Y1961', 'Y1962','Y1963', 'Y1964'])
cleaned_temp.head()

,Area,Months,Element,Unit,Y1965,Y1966,Y1967,Y1968,Y1969,Y1970,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,Afghanistan,January,Temperature change,°C,1.868,3.629,-1.432,0.389,-2.298,0.804,...,3.601,1.179,-0.583,1.233,1.755,1.943,3.416,1.201,1.996,2.951
1,Afghanistan,January,Standard Deviation,°C,1.950,1.950,1.950,1.950,1.950,1.950,...,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950
2,Afghanistan,February,Temperature change,°C,-0.096,3.397,0.296,-2.055,-3.167,1.809,...,1.212,0.321,-3.201,1.494,-3.187,2.699,2.251,-0.323,2.705,0.086
3,Afghanistan,February,Standard Deviation,°C,2.597,2.597,2.597,2.597,2.597,2.597,...,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597
4,Afghanistan,March,Temperature change,°C,-0.909,-0.069,-0.759,0.496,2.481,-0.915,...,3.390,0.748,-0.527,2.246,-0.076,-0.497,2.296,0.834,4.418,0.234

In [41]:
# Extract only temperature change data
new_kaggle = cleaned_temp[cleaned_temp["Element"]=="Temperature change"]
new_kaggle.head(60)

,Area,Months,Element,Unit,Y1965,Y1966,Y1967,Y1968,Y1969,Y1970,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,Afghanistan,January,Temperature change,°C,1.868,3.629,-1.432,0.389,-2.298,0.804,...,3.601,1.179,-0.583,1.233,1.755,1.943,3.416,1.201,1.996,2.951
2,Afghanistan,February,Temperature change,°C,-0.096,3.397,0.296,-2.055,-3.167,1.809,...,1.212,0.321,-3.201,1.494,-3.187,2.699,2.251,-0.323,2.705,0.086
4,Afghanistan,March,Temperature change,°C,-0.909,-0.069,-0.759,0.496,2.481,-0.915,...,3.390,0.748,-0.527,2.246,-0.076,-0.497,2.296,0.834,4.418,0.234
6,Afghanistan,April,Temperature change,°C,-1.816,-1.192,-1.496,-0.590,-0.770,1.439,...,2.591,1.712,1.417,-0.052,0.585,1.589,0.980,1.252,1.442,0.899
8,Afghanistan,May,Temperature change,°C,-0.190,-0.192,-1.307,-1.841,-0.977,1.864,...,1.419,3.643,0.909,1.201,0.959,1.862,3.246,3.280,0.855,0.647
10,Afghanistan,June,Temperature change,°C,-0.422,1.274,-0.722,0.292,-0.270,0.544,...,0.594,2.450,0.305,1.924,1.492,1.289,1.586,2.002,1.786,-0.289
12,Afghanistan,July,Temperature change,°C,0.116,-0.267,0.332,-0.256,-0.024,-0.534,...,0.494,0.532,0.973,1.126,0.671,1.092,1.079,0.901,1.815,1.885
14,Afghanistan,August,Temperature change,°C,-0.686,0.049,0.055,-0.155,-0.442,1.867,...,0.587,1.930,1.356,0.886,0.706,0.589,0.311,0.102,0.982,0.773
16,Afghanistan,September,Temperature change,°C,-0.661,-0.403,0.583,-0.269,-0.847,0.005,...,0.030,1.408,0.495,2.586,2.268,0.172,3.016,0.930,1.063,2.004
18,Afghanistan,October,Temperature change,°C,2.211,-0.428,-0.800,-0.611,1.103,0.542,...,2.927,1.339,0.827,1.691,1.134,1.894,0.792,2.092,-0.103,1.264
20,Afghanistan,November,Temperature change,°C,1.820,-2.574,1.245,0.471,-0.742,0.881,...,0.975,1.000,1.042,0.975,-0.403,0.512,-1.345,2.089,0.882,-1.051
22,Afghanistan,December,Temperature change,°C,-1.115,-0.327,-0.347,0.056,1.985,-0.186,...,-0.154,-1.789,-0.467,-0.216,0.005,0.048,3.429,0.441,1.311,1.426
24,Afghanistan,DecJanFeb,Temperature change,°C,-0.621,1.970,-0.488,-0.671,-1.803,1.533,...,1.921,0.449,-1.858,0.753,-0.549,1.549,1.905,1.436,1.714,1.449
26,Afghanistan,MarAprMay,Temperature change,°C,-0.972,-0.484,-1.187,-0.645,0.245,0.796,...,2.467,2.034,0.600,1.132,0.489,0.985,2.174,1.789,2.238,0.593
28,Afghanistan,JunJulAug,Temperature change,°C,-0.331,0.352,-0.112,-0.040,-0.245,0.626,...,0.558,1.637,0.878,1.312,0.956,0.990,0.992,1.002,1.528,0.790
30,Afghanistan,SepOctNov,Temperature change,°C,1.123,-1.135,0.343,-0.136,-0.162,0.476,...,1.311,1.249,0.788,1.751,1.000,0.859,0.821,1.704,0.614,0.739
32,Afghanistan,Meteorological year,Temperature change,°C,-0.200,0.176,-0.361,-0.373,-0.491,0.858,...,1.564,1.342,0.102,1.237,0.474,1.096,1.473,1.483,1.524,0.893
34,Albania,January,Temperature change,°C,0.635,-1.501,-1.887,-2.290,-0.868,1.797,...,1.137,0.812,-1.004,1.760,3.583,1.083,1.530,-2.470,2.304,-0.816
36,Albania,February,Temperature change,°C,-4.319,2.845,-1.224,1.316,0.453,0.136,...,0.879,0.554,-2.714,1.219,3.502,0.378,4.611,2.622,0.765,1.563
38,Albania,March,Temperature change,°C,0.093,-0.636,0.477,-0.347,-0.139,-0.031,...,1.079,1.521,2.081,1.420,2.363,0.777,1.670,3.419,1.768,3.119
40,Albania,April,Temperature change,°C,-1.076,1.285,-0.665,2.185,-0.649,0.307,...,1.804,1.350,1.320,2.509,1.076,0.607,3.554,0.938,4.878,1.866
42,Albania,May,Temperature change,°C,-0.781,-0.368,0.345,2.723,2.359,-1.951,...,0.938,0.687,0.916,2.107,0.079,2.341,0.141,1.424,3.424,-0.822
44,Albania,June,Temperature change,°C,0.174,0.128,-1.463,-0.263,-1.001,0.128,...,0.847,1.384,3.084,0.896,1.052,1.278,1.974,2.879,1.709,3.474
46,Albania,July,Temperature change,°C,0.899,-0.083,0.129,-0.099,-1.418,-0.467,...,1.676,1.228,3.824,1.452,0.353,3.828,2.373,2.783,1.538,1.873
48,Albania,August,Temperature change,°C,-1.335,0.830,0.975,-1.870,-0.562,0.184,...,2.518,2.444,3.130,2.822,1.440,3.174,1.414,3.522,2.704,3.336
50,Albania,September,Temperature change,°C,0.457,0.291,0.518,-0.427,0.654,0.217,...,0.296,3.838,2.487,0.880,0.264,2.707,0.948,0.905,2.328,2.706
52,Albania,October,Temperature change,°C,-0.395,3.118,1.674,-0.305,-0.096,-1.109,...,-0.408,-0.083,2.858,1.783,1.068,1.732,1.018,0.644,2.789,3.004
54,Albania,November,Temperature change,°C,0.490,-0.275,0.682,0.709,1.631,0.127,...,2.859,-0.711,2.557,1.922,2.048,1.683,0.625,0.253,2.101,3.585
56,Albania,December,Temperature change,°C,0.972,-0.563,-0.474,-0.655,-0.885,0.011,...,0.453,0.703,-0.831,-0.035,1.106,0.509,-0.872,0.476,0.040,2.052
58,Albania,DecJanFeb,Temperature change,°C,-1.078,0.772,-1.225,-0.483,-0.357,0.349,...,1.306,0.606,-1.005,0.716,2.350,0.856,2.217,-0.240,1.182,0.262
60,Albania,MarAprMay,Temperature change,°C,-0.588,0.094,0.052,1.520,0.524,-0.558,...,1.274,1.186,1.439,2.012,1.173,1.242,1.788,1.927,3.357,1.388
62,Albania,JunJulAug,Temperature change,°C,-0.087,0.292,-0.120,-0.744,-0.994,-0.052,...,1.680,1.685,3.346,1.723,0.948,2.760,1.920,3.061,1.984,2.894
64,Albania,SepOctNov,Temperature change,°C,0.184,1.045,0.958,-0.008,0.730,-0.255,...,0.916,1.015,2.634,1.528,1.127,2.041,0.864,0.601,2.406,3.098
66,Albania,Meteorological year,Temperature change,°C,-0.392,0.551,-0.084,0.071,-0.024,-0.129,...,1.294,1.123,1.603,1.495,1.399,1.725,1.697,1.337,2.232,1.911
68,Algeria,January,Temperature change,°C,0.010,1.880,-0.871,-1.491,0.773,1.757,...,2.197,1.496,-1.140,0.226,1.373,-0.519,2.288,-1.669,1.504,-0.874
70,Algeria,February,Temperature change,°C,-0.713,2.307,0.083,0.608,1.733,0.127,...,4.067,-0.643,-2.680,-0.835,1.095,-0.477,1.731,2.156,-0.301,-1.145
72,Algeria,March,Temperature change,°C,0.729,-1.618,0.659,0.278,2.266,0.156,...,3.386,1.790,0.193,2.801,0.318,-0.274,-0.001,2.054,1.985,0.764
74,Algeria,April,Temperature change,°C,-1.376,0.876,-0.176,1.337,-0.669,-0.231,...,3.921,2.375,1.234,2.213,2.965,3.222,3.738,2.258,2.286,1.169
76,Algeria,May,Temperature change,°C,0.337,-0.416,0.607,-0.246,0.532,-0.487,...,1.227,1.260,2.491,1.325,2.396,3.218,2.584,4.114,1.001,1.743
78,Algeria,June,Temperature change,°C,-0.808,1.100,-0.720,-0.862,-0.329,0.311,...,1.568,0.912,3.151,0.838,0.857,0.946,1.976,2.062,1.104,1.861
80,Algeria,July,Temperature change,°C,0.652,0.540,-0.807,-0.158,-1.331,-0.475,...,2.096,1.858,2.388,1.728,2.147,1.115,1.443,1.827,3.442,2.367
82,Algeria,August,Temperature change,°C,-0.837,0.728,-0.170,0.038,-0.287,0.762,...,1.783,1.617,1.878,0.498,2.270,1.921,0.870,1.734,0.601,2.388
84,Algeria,September,Temperature change,°C,-0.845,-0.074,-0.097,0.389,-0.479,0.138,...,1.395,2.639,1.317,1.021,2.998,1.539,1.738,1.534,1.562,2.192
86,Algeria,October,Temperature change,°C,1.313,0.106,0.798,0.141,-0.596,-0.202,...,1.687,0.395,2.686,3.903,2.470,2.734,3.334,0.969,1.295,2.076
88,Algeria,November,Temperature change,°C,0.618,-1.123,1.287,0.728,1.253,0.103,...,1.789,1.442,2.920,0.720,2.357,1.248,1.636,0.708,1.511,0.899
90,Algeria,December,Temperature change,°C,0.537,-0.877,-1.709,0.279,-1.065,0.045,...,2.768,0.421,0.771,0.041,0.018,1.056,1.815,-0.081,1.255,2.361
92,Algeria,DecJanFeb,Temperature change,°C,-0.470,1.575,-0.555,-0.864,0.928,0.273,...,3.150,1.207,-1.133,0.054,0.836,-0.326,1.692,0.767,0.374,-0.255
94,Algeria,MarAprMay,Temperature change,°C,-0.103,-0.386,0.363,0.456,0.710,-0.187,...,2.845,1.808,1.306,2.113,1.893,2.055,2.107,2.809,1.757,1.225
96,Algeria,JunJulAug,Temperature change,°C,-0.331,0.789,-0.566,-0.327,-0.649,0.199,...,1.816,1.462,2.472,1.021,1.758,1.327,1.430,1.874,1.716,2.205
98,Algeria,SepOctNov,Temperature change,°C,0.362,-0.364,0.663,0.419,0.059,0.013,...,1.624,1.492,2.308,1.881,2.608,1.840,2.236,1.070,1.456,1.722
100,Algeria,Meteorological year,Temperature change,°C,-0.135,0.404,-0.024,-0.079,0.262,0.075,...,2.359,1.492,1.238,1.267,1.774,1.224,1.866,1.630,1.326,1.224
102,American Samoa,January,Temperature change,°C,-0.836,0.137,-0.099,0.068,0.315,0.000,...,3.010,0.379,0.843,0.534,0.553,0.993,1.863,1.713,0.763,1.513
104,American Samoa,February,Temperature change,°C,-0.859,0.559,-0.459,-0.463,0.133,0.275,...,1.015,-0.098,0.702,1.182,1.466,1.526,2.606,0.806,0.956,1.506
106,American Samoa,March,Temperature change,°C,-0.625,0.675,0.204,-0.297,0.236,-0.496,...,1.171,0.620,0.320,1.020,NaN,NaN,NaN,NaN,NaN,NaN
108,American Samoa,April,Temperature change,°C,-0.471,-0.165,-0.492,-1.042,0.279,0.050,...,-0.930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,American Samoa,May,Temperature change,°C,-0.232,0.013,-0.485,-0.431,-0.151,0.357,...,0.906,0.901,0.606,1.671,0.997,0.697,1.147,1.297,1.097,1.047
112,American Samoa,June,Temperature change,°C,-0.708,0.132,-0.764,0.149,0.404,0.076,...,0.702,1.052,0.665,1.285,0.756,0.566,1.176,0.976,1.476,1.476
114,American Samoa,July,Temperature change,°C,-0.230,0.449,-0.628,-0.230,-0.137,0.090,...,1.616,1.967,0.674,1.059,0.420,0.580,1.010,1.160,0.960,1.360
116,American Samoa,August,Temperature change,°C,-0.476,-0.185,-0.468,-0.613,-0.356,-0.264,...,1.313,1.058,1.133,1.158,0.849,0.279,1.579,1.329,0.879,1.879
118,American Samoa,September,Temperature change,°C,-0.298,-0.079,0.004,0.087,-0.293,-0.453,...,0.799,1.185,1.354,1.314,1.718,0.748,1.408,1.758,1.308,1.658

In [42]:
new_kaggle.reset_index(drop=True).head()

,Area,Months,Element,Unit,Y1965,Y1966,Y1967,Y1968,Y1969,Y1970,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,Afghanistan,January,Temperature change,°C,1.868,3.629,-1.432,0.389,-2.298,0.804,...,3.601,1.179,-0.583,1.233,1.755,1.943,3.416,1.201,1.996,2.951
1,Afghanistan,February,Temperature change,°C,-0.096,3.397,0.296,-2.055,-3.167,1.809,...,1.212,0.321,-3.201,1.494,-3.187,2.699,2.251,-0.323,2.705,0.086
2,Afghanistan,March,Temperature change,°C,-0.909,-0.069,-0.759,0.496,2.481,-0.915,...,3.390,0.748,-0.527,2.246,-0.076,-0.497,2.296,0.834,4.418,0.234
3,Afghanistan,April,Temperature change,°C,-1.816,-1.192,-1.496,-0.590,-0.770,1.439,...,2.591,1.712,1.417,-0.052,0.585,1.589,0.980,1.252,1.442,0.899
4,Afghanistan,May,Temperature change,°C,-0.190,-0.192,-1.307,-1.841,-0.977,1.864,...,1.419,3.643,0.909,1.201,0.959,1.862,3.246,3.280,0.855,0.647

In [43]:
# Drop quarters and Meteorological year
# A typical meteorological year (TMY) is a set of meteorological data with data values for every hour 
# in a year for a given geographical location. The data are selected from hourly data in a longer time period 
# (normally 10 years or more). For each month in the year the data have been selected from the year that was considered most 
# "typical" for that month. For instance, January might be from 2007, February from 2012 and so on.
delete_me = new_kaggle[new_kaggle['Months'] == "MarAprMay"].index
new_kaggle.drop(delete_me , inplace=True)
delete_me1 = new_kaggle[new_kaggle['Months'] == "JunJulAug"].index
new_kaggle.drop(delete_me1 , inplace=True)
delete_me2 = new_kaggle[new_kaggle['Months'] == "SepOctNov"].index
new_kaggle.drop(delete_me2 , inplace=True)
delete_me2 = new_kaggle[new_kaggle['Months'] == "DecJanFeb"].index
new_kaggle.drop(delete_me2 , inplace=True)
delete_me3 = new_kaggle[new_kaggle['Months'] == "Meteorological year"].index
new_kaggle.drop(delete_me3 , inplace=True)

C:\Users\elesh\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [44]:
# new_kaggle.head(60)

In [57]:
# Find average change for one country for 1 year
areas = new_kaggle['Area']
# years = new_kaggle['']

for area in areas:
    (area['Y1965']).mean()

TypeError: string indices must be integers

In [55]:
areas

0       Afghanistan
2       Afghanistan
4       Afghanistan
6       Afghanistan
8       Afghanistan
           ...
9636           OECD
9638           OECD
9640           OECD
9642           OECD
9644           OECD
Name: Area, Length: 3408, dtype: object

In [46]:
afg = new_kaggle[new_kaggle['Area']== "Afghanistan"]
afg

,Area,Months,Element,Unit,Y1965,Y1966,Y1967,Y1968,Y1969,Y1970,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,Afghanistan,January,Temperature change,°C,1.868,3.629,-1.432,0.389,-2.298,0.804,...,3.601,1.179,-0.583,1.233,1.755,1.943,3.416,1.201,1.996,2.951
2,Afghanistan,February,Temperature change,°C,-0.096,3.397,0.296,-2.055,-3.167,1.809,...,1.212,0.321,-3.201,1.494,-3.187,2.699,2.251,-0.323,2.705,0.086
4,Afghanistan,March,Temperature change,°C,-0.909,-0.069,-0.759,0.496,2.481,-0.915,...,3.390,0.748,-0.527,2.246,-0.076,-0.497,2.296,0.834,4.418,0.234
6,Afghanistan,April,Temperature change,°C,-1.816,-1.192,-1.496,-0.590,-0.770,1.439,...,2.591,1.712,1.417,-0.052,0.585,1.589,0.980,1.252,1.442,0.899
8,Afghanistan,May,Temperature change,°C,-0.190,-0.192,-1.307,-1.841,-0.977,1.864,...,1.419,3.643,0.909,1.201,0.959,1.862,3.246,3.280,0.855,0.647
10,Afghanistan,June,Temperature change,°C,-0.422,1.274,-0.722,0.292,-0.270,0.544,...,0.594,2.450,0.305,1.924,1.492,1.289,1.586,2.002,1.786,-0.289
12,Afghanistan,July,Temperature change,°C,0.116,-0.267,0.332,-0.256,-0.024,-0.534,...,0.494,0.532,0.973,1.126,0.671,1.092,1.079,0.901,1.815,1.885
14,Afghanistan,August,Temperature change,°C,-0.686,0.049,0.055,-0.155,-0.442,1.867,...,0.587,1.930,1.356,0.886,0.706,0.589,0.311,0.102,0.982,0.773
16,Afghanistan,September,Temperature change,°C,-0.661,-0.403,0.583,-0.269,-0.847,0.005,...,0.030,1.408,0.495,2.586,2.268,0.172,3.016,0.930,1.063,2.004
18,Afghanistan,October,Temperature change,°C,2.211,-0.428,-0.800,-0.611,1.103,0.542,...,2.927,1.339,0.827,1.691,1.134,1.894,0.792,2.092,-0.103,1.264
20,Afghanistan,November,Temperature change,°C,1.820,-2.574,1.245,0.471,-0.742,0.881,...,0.975,1.000,1.042,0.975,-0.403,0.512,-1.345,2.089,0.882,-1.051
22,Afghanistan,December,Temperature change,°C,-1.115,-0.327,-0.347,0.056,1.985,-0.186,...,-0.154,-1.789,-0.467,-0.216,0.005,0.048,3.429,0.441,1.311,1.426

In [34]:
len(afg)

12

In [48]:
(afg['Y1965']).mean()

0.010000000000000009

### Export Cleaned Datasets to SQLite

In [ ]:
# Create the connection using the imported create_engine function and then invoking the connect method on it
connection_string = f"postgres:{postgres_password}@localhost:5432/final_project"
engine = create_engine(f'postgresql://{connection_string}')

In [ ]:
# Check for tables
# engine.table_names()

In [ ]:
# Load dataframes to postgres
emission_goal_combine.to_sql(name='emission_goals', con=engine, if_exists='replace', index=False)

In [ ]:
bp_co2_all_cleaned.to_sql(name='emissions', con=engine, if_exists='replace', index=True)
bp_nonrewablec.to_sql(name='nonrenewable_energy', con=engine, if_exists='replace', index=True)
bp_rc_all_cleaned.to_sql(name='renewable_energy', con=engine, if_exists='replace', index=True)
bp_ec_all_cleaned.to_sql(name='energy_consumption', con=engine, if_exists='replace', index=True)

In [ ]:
data_combine.to_sql(name='bp_all', con=engine, if_exists='replace', index=True)

In [ ]:
new_data_df.to_sql(name='emission_benchmarks', con=engine, if_exists='replace', index=False)

In [ ]:
## Create the connection using the imported create_engine function and then invoking the connect method on it
# engine = create_engine('sqlite:///VAERS.db', echo=False)
# sqlite_connection = engine.connect()

In [ ]:
# ## Set a variable name with the string of a table name
# sqlite_vaers = "2021VAERS"
# merge_all.to_sql(sqlite_vaers, sqlite_connection, if_exists='fail')

In [ ]:
# ## Close the database connection 
# sqlite_connection.close()