In [3]:
import pandas as pd
import numpy as np
from pandas import DataFrame
from sqlalchemy import create_engine
from bs4 import BeautifulSoup
import json
import requests
from pandas import json_normalize
import datetime

In [37]:
#Read the csv file without header 
goal_csv = "2030emission_goals.csv"
goal_df = pd.read_csv(goal_csv, header=None)
goal_df

,0,1,2,3,4,5
0,Number of parties that have submitted an I/NDC,192,CARBON BRIEF'S I/NDC TRACKER,Parties that haven't submitted an I/NDC,3,NaN
1,NaN,Share of global emissions covered by I/NDCs,87.60%,DATA SUMMARY,Emissions not covered,12.40%
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Country,Date,Summary of the I/NDC,Link to I/NDC,Share of 2012 GHG
4,NaN,China,30/06/2015,"A peak in carbon dioxide emissions by 2030, wi...",http://www4.unfccc.int/ndcregistry/PublishedDo...,23.75%
...,...,...,...,...,...,...
168,NaN,Montenegro,23/09/2015,A 30% reduction in emissions by 2030 compared ...,NaN,0.00%
169,NaN,Monaco,29/07/2015,A 50% reduction in greenhouse gas emissions by...,NaN,0.00%
170,NaN,Andorra,1/5/15,A 37% reduction in greenhouse gas emissions fr...,NaN,0.00%
171,NaN,Liechtenstein,23/04/2015,A 40% reduction on 1990 levels by 2030. This i...,NaN,0.00%
172,Published by Google Sheets–Report Abuse–Update...,NaN,NaN,NaN,NaN,NaN

In [38]:
#Drop first 3 rows
goal_df = goal_df.iloc[3:]

In [39]:
# new_header = df.iloc[0] #grab the first row for the header
# df.columns = new_header #set the header row as the df header

# Set the first row as header
goal_df.columns = goal_df.iloc[0]
goal_df

3,NaN,Country,Date,Summary of the I/NDC,Link to I/NDC,Share of 2012 GHG
3,NaN,Country,Date,Summary of the I/NDC,Link to I/NDC,Share of 2012 GHG
4,NaN,China,30/06/2015,"A peak in carbon dioxide emissions by 2030, wi...",http://www4.unfccc.int/ndcregistry/PublishedDo...,23.75%
5,NaN,USA,31/03/2015,[The US plans to withdraw from Paris and not m...,http://www4.unfccc.int/ndcregistry/PublishedDo...,12.10%
6,NaN,EU,6/3/15,At least a 40% domestic reduction in greenhous...,http://www4.unfccc.int/ndcregistry/PublishedDo...,8.97%
7,NaN,India,1/10/15,A 33-35% reduction in emissions intensity by 2...,http://www4.unfccc.int/ndcregistry/PublishedDo...,5.73%
...,...,...,...,...,...,...
168,NaN,Montenegro,23/09/2015,A 30% reduction in emissions by 2030 compared ...,NaN,0.00%
169,NaN,Monaco,29/07/2015,A 50% reduction in greenhouse gas emissions by...,NaN,0.00%
170,NaN,Andorra,1/5/15,A 37% reduction in greenhouse gas emissions fr...,NaN,0.00%
171,NaN,Liechtenstein,23/04/2015,A 40% reduction on 1990 levels by 2030. This i...,NaN,0.00%
172,Published by Google Sheets–Report Abuse–Update...,NaN,NaN,NaN,NaN,NaN

In [40]:
# Drop the first row
goal_df = goal_df.iloc[1:]
goal_df

3,NaN,Country,Date,Summary of the I/NDC,Link to I/NDC,Share of 2012 GHG
4,NaN,China,30/06/2015,"A peak in carbon dioxide emissions by 2030, wi...",http://www4.unfccc.int/ndcregistry/PublishedDo...,23.75%
5,NaN,USA,31/03/2015,[The US plans to withdraw from Paris and not m...,http://www4.unfccc.int/ndcregistry/PublishedDo...,12.10%
6,NaN,EU,6/3/15,At least a 40% domestic reduction in greenhous...,http://www4.unfccc.int/ndcregistry/PublishedDo...,8.97%
7,NaN,India,1/10/15,A 33-35% reduction in emissions intensity by 2...,http://www4.unfccc.int/ndcregistry/PublishedDo...,5.73%
8,NaN,Brazil,28/09/2015,"A 37% reduction in emissions by 2025, compared...",http://www4.unfccc.int/ndcregistry/PublishedDo...,5.70%
...,...,...,...,...,...,...
168,NaN,Montenegro,23/09/2015,A 30% reduction in emissions by 2030 compared ...,NaN,0.00%
169,NaN,Monaco,29/07/2015,A 50% reduction in greenhouse gas emissions by...,NaN,0.00%
170,NaN,Andorra,1/5/15,A 37% reduction in greenhouse gas emissions fr...,NaN,0.00%
171,NaN,Liechtenstein,23/04/2015,A 40% reduction on 1990 levels by 2030. This i...,NaN,0.00%
172,Published by Google Sheets–Report Abuse–Update...,NaN,NaN,NaN,NaN,NaN

In [41]:
# Drop 5th column
goal_df = goal_df.drop(columns =['Link to I/NDC'])
goal_df

3,NaN,Country,Date,Summary of the I/NDC,Share of 2012 GHG
4,NaN,China,30/06/2015,"A peak in carbon dioxide emissions by 2030, wi...",23.75%
5,NaN,USA,31/03/2015,[The US plans to withdraw from Paris and not m...,12.10%
6,NaN,EU,6/3/15,At least a 40% domestic reduction in greenhous...,8.97%
7,NaN,India,1/10/15,A 33-35% reduction in emissions intensity by 2...,5.73%
8,NaN,Brazil,28/09/2015,"A 37% reduction in emissions by 2025, compared...",5.70%
...,...,...,...,...,...
168,NaN,Montenegro,23/09/2015,A 30% reduction in emissions by 2030 compared ...,0.00%
169,NaN,Monaco,29/07/2015,A 50% reduction in greenhouse gas emissions by...,0.00%
170,NaN,Andorra,1/5/15,A 37% reduction in greenhouse gas emissions fr...,0.00%
171,NaN,Liechtenstein,23/04/2015,A 40% reduction on 1990 levels by 2030. This i...,0.00%
172,Published by Google Sheets–Report Abuse–Update...,NaN,NaN,NaN,NaN

In [46]:
# Drop 1st column
goal_df = goal_df.drop([goal_df.columns[0]], axis=1)
goal_df

3,Date,Summary of the I/NDC,Share of 2012 GHG
4,30/06/2015,"A peak in carbon dioxide emissions by 2030, wi...",23.75%
5,31/03/2015,[The US plans to withdraw from Paris and not m...,12.10%
6,6/3/15,At least a 40% domestic reduction in greenhous...,8.97%
7,1/10/15,A 33-35% reduction in emissions intensity by 2...,5.73%
8,28/09/2015,"A 37% reduction in emissions by 2025, compared...",5.70%
...,...,...,...
168,23/09/2015,A 30% reduction in emissions by 2030 compared ...,0.00%
169,29/07/2015,A 50% reduction in greenhouse gas emissions by...,0.00%
170,1/5/15,A 37% reduction in greenhouse gas emissions fr...,0.00%
171,23/04/2015,A 40% reduction on 1990 levels by 2030. This i...,0.00%
172,NaN,NaN,NaN