In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
# Read the csv file into a pandas DataFrame
emission_goals = pd.read_csv('clean_data/emission_goals.csv')
emission_goals

,country,2030,2040,2050,1965.0_all_energy,1966.0_all_energy,1967.0_all_energy,1968.0_all_energy,1969.0_all_energy,1970.0_all_energy,...,2010.0_co2_emission,2011.0_co2_emission,2012.0_co2_emission,2013.0_co2_emission,2014.0_co2_emission,2015.0_co2_emission,2016.0_co2_emission,2017.0_co2_emission,2018.0_co2_emission,2019.0_co2_emission
0,Global,50-125,5-25,<0,155.690938,164.097213,170.274511,180.646875,192.857279,205.007079,...,31085.534841,31973.369818,32273.531532,32795.554106,32804.718691,32787.197673,32936.066036,33279.491334,34007.891035,34169.000782
1,US,30-130,0-32,<0,52.433795,55.383038,57.311776,60.799094,64.049612,66.215508,...,5485.715925,5336.435925,5089.974540,5249.595898,5254.565096,5141.406746,5042.431426,4983.869718,5116.785715,4964.693088
2,EU,75-80,0-5,<0,42.093184,43.282622,44.509488,47.391263,50.927589,54.195380,...,3922.934995,3800.361504,3737.698716,3653.468215,3445.591925,3486.935193,3498.502547,3527.146451,3466.482504,3330.444758
3,Brazil,0-20,<0,<0,0.969469,1.057605,1.095653,1.252840,1.367832,1.585817,...,398.324213,423.761618,442.858031,482.871255,503.779772,487.040178,450.367978,457.229289,442.250684,441.299916
4,India,115-155,5,<0,2.217659,2.285377,2.355911,2.517670,2.790898,2.729549,...,1660.654080,1735.150560,1848.132873,1929.353035,2083.540801,2149.379180,2242.892441,2329.816567,2452.501157,2480.354461
5,China,100-110,0-5,<0,5.516043,5.995001,5.391341,5.445350,6.627664,8.486606,...,8143.438769,8824.313535,9001.257445,9244.003274,9239.855878,9185.990809,9137.626592,9297.988543,9507.109644,9825.801775
6,South Africa,45-377,5-10,<0,1.275199,1.283121,1.336141,1.410133,1.451920,1.517304,...,476.665493,467.761278,463.782634,464.160481,469.114585,451.706682,470.509701,465.805487,470.377753,478.823071
7,Indonesia,50-255,5-30,<0,0.303080,0.300495,0.296711,0.316207,0.357009,0.382341,...,428.016230,480.059094,513.002788,532.869390,486.137994,497.934985,501.997264,526.971609,580.719627,632.085380

In [3]:
list(emission_goals.columns)

['country',
 '2030',
 '2040',
 '2050',
 '1965.0_all_energy',
 '1966.0_all_energy',
 '1967.0_all_energy',
 '1968.0_all_energy',
 '1969.0_all_energy',
 '1970.0_all_energy',
 '1971.0_all_energy',
 '1972.0_all_energy',
 '1973.0_all_energy',
 '1974.0_all_energy',
 '1975.0_all_energy',
 '1976.0_all_energy',
 '1977.0_all_energy',
 '1978.0_all_energy',
 '1979.0_all_energy',
 '1980.0_all_energy',
 '1981.0_all_energy',
 '1982.0_all_energy',
 '1983.0_all_energy',
 '1984.0_all_energy',
 '1985.0_all_energy',
 '1986.0_all_energy',
 '1987.0_all_energy',
 '1988.0_all_energy',
 '1989.0_all_energy',
 '1990.0_all_energy',
 '1991.0_all_energy',
 '1992.0_all_energy',
 '1993.0_all_energy',
 '1994.0_all_energy',
 '1995.0_all_energy',
 '1996.0_all_energy',
 '1997.0_all_energy',
 '1998.0_all_energy',
 '1999.0_all_energy',
 '2000.0_all_energy',
 '2001.0_all_energy',
 '2002.0_all_energy',
 '2003.0_all_energy',
 '2004.0_all_energy',
 '2005.0_all_energy',
 '2006.0_all_energy',
 '2007.0_all_energy',
 '2008.0_all_energy',
 '2009.0_all_energy',
 '2010.0_all_energy',
 '2011.0_all_energy',
 '2012.0_all_energy',
 '2013.0_all_energy',
 '2014.0_all_energy',
 '2015.0_all_energy',
 '2016.0_all_energy',
 '2017.0_all_energy',
 '2018.0_all_energy',
 '2019.0_all_energy',
 '1965.0_renewable_per',
 '1966.0_renewable_per',
 '1967.0_renewable_per',
 '1968.0_renewable_per',
 '1969.0_renewable_per',
 '1970.0_renewable_per',
 '1971.0_renewable_per',
 '1972.0_renewable_per',
 '1973.0_renewable_per',
 '1974.0_renewable_per',
 '1975.0_renewable_per',
 '1976.0_renewable_per',
 '1977.0_renewable_per',
 '1978.0_renewable_per',
 '1979.0_renewable_per',
 '1980.0_renewable_per',
 '1981.0_renewable_per',
 '1982.0_renewable_per',
 '1983.0_renewable_per',
 '1984.0_renewable_per',
 '1985.0_renewable_per',
 '1986.0_renewable_per',
 '1987.0_renewable_per',
 '1988.0_renewable_per',
 '1989.0_renewable_per',
 '1990.0_renewable_per',
 '1991.0_renewable_per',
 '1992.0_renewable_per',
 '1993.0_renewable_per',
 '1994.0_renewable_per',
 '1995.0_renewable_per',
 '1996.0_renewable_per',
 '1997.0_renewable_per',
 '1998.0_renewable_per',
 '1999.0_renewable_per',
 '2000.0_renewable_per',
 '2001.0_renewable_per',
 '2002.0_renewable_per',
 '2003.0_renewable_per',
 '2004.0_renewable_per',
 '2005.0_renewable_per',
 '2006.0_renewable_per',
 '2007.0_renewable_per',
 '2008.0_renewable_per',
 '2009.0_renewable_per',
 '2010.0_renewable_per',
 '2011.0_renewable_per',
 '2012.0_renewable_per',
 '2013.0_renewable_per',
 '2014.0_renewable_per',
 '2015.0_renewable_per',
 '2016.0_renewable_per',
 '2017.0_renewable_per',
 '2018.0_renewable_per',
 '2019.0_renewable_per',
 '1965.0_nonrenewable_per',
 '1966.0_nonrenewable_per',
 '1967.0_nonrenewable_per',
 '1968.0_nonrenewable_per',
 '1969.0_nonrenewable_per',
 '1970.0_nonrenewable_per',
 '1971.0_nonrenewable_per',
 '1972.0_nonrenewable_per',
 '1973.0_nonrenewable_per',
 '1974.0_nonrenewable_per',
 '1975.0_nonrenewable_per',
 '1976.0_nonrenewable_per',
 '1977.0_nonrenewable_per',
 '1978.0_nonrenewable_per',
 '1979.0_nonrenewable_per',
 '1980.0_nonrenewable_per',
 '1981.0_nonrenewable_per',
 '1982.0_nonrenewable_per',
 '1983.0_nonrenewable_per',
 '1984.0_nonrenewable_per',
 '1985.0_nonrenewable_per',
 '1986.0_nonrenewable_per',
 '1987.0_nonrenewable_per',
 '1988.0_nonrenewable_per',
 '1989.0_nonrenewable_per',
 '1990.0_nonrenewable_per',
 '1991.0_nonrenewable_per',
 '1992.0_nonrenewable_per',
 '1993.0_nonrenewable_per',
 '1994.0_nonrenewable_per',
 '1995.0_nonrenewable_per',
 '1996.0_nonrenewable_per',
 '1997.0_nonrenewable_per',
 '1998.0_nonrenewable_per',
 '1999.0_nonrenewable_per',
 '2000.0_nonrenewable_per',
 '2001.0_nonrenewable_per',
 '2002.0_nonrenewable_per',
 '2003.0_nonrenewable_per',
 '2004.0_nonrenewable_per',
 '2005.0_nonrenewable_per',
 '2006.0_nonrenewable_per',
 '2007.0_nonrenewable_per',
 '2008.0_nonrenewable_per',
 '2009.0_nonrenewable_per',
 '2010.0_nonrenewable_per',
 '2011.0_nonrenewable_per',
 '2012.0_nonrenewable_per',
 '2013.0_nonrenewable_per',
 '2014.0_nonrenewable_per',
 '2015.0_nonrenewable_per',
 '2016.0_nonrenewable_per',
 '2017.0_nonrenewable_per',
 '2018.0_nonrenewable_per',
 '2019.0_nonrenewable_per',
 '1965.0_co2_emission',
 '1966.0_co2_emission',
 '1967.0_co2_emission',
 '1968.0_co2_emission',
 '1969.0_co2_emission',
 '1970.0_co2_emission',
 '1971.0_co2_emission',
 '1972.0_co2_emission',
 '1973.0_co2_emission',
 '1974.0_co2_emission',
 '1975.0_co2_emission',
 '1976.0_co2_emission',
 '1977.0_co2_emission',
 '1978.0_co2_emission',
 '1979.0_co2_emission',
 '1980.0_co2_emission',
 '1981.0_co2_emission',
 '1982.0_co2_emission',
 '1983.0_co2_emission',
 '1984.0_co2_emission',
 '1985.0_co2_emission',
 '1986.0_co2_emission',
 '1987.0_co2_emission',
 '1988.0_co2_emission',
 '1989.0_co2_emission',
 '1990.0_co2_emission',
 '1991.0_co2_emission',
 '1992.0_co2_emission',
 '1993.0_co2_emission',
 '1994.0_co2_emission',
 '1995.0_co2_emission',
 '1996.0_co2_emission',
 '1997.0_co2_emission',
 '1998.0_co2_emission',
 '1999.0_co2_emission',
 '2000.0_co2_emission',
 '2001.0_co2_emission',
 '2002.0_co2_emission',
 '2003.0_co2_emission',
 '2004.0_co2_emission',
 '2005.0_co2_emission',
 '2006.0_co2_emission',
 '2007.0_co2_emission',
 '2008.0_co2_emission',
 '2009.0_co2_emission',
 '2010.0_co2_emission',
 '2011.0_co2_emission',
 '2012.0_co2_emission',
 '2013.0_co2_emission',
 '2014.0_co2_emission',
 '2015.0_co2_emission',
 '2016.0_co2_emission',
 '2017.0_co2_emission',
 '2018.0_co2_emission',
 '2019.0_co2_emission']

In [4]:
emission_goals['2030']

0     50-125
1     30-130
2      75-80
3       0-20
4    115-155
5    100-110
6     45-377
7     50-255
Name: 2030, dtype: object

In [5]:
emission_goals['country']

0          Global
1              US
2              EU
3          Brazil
4           India
5           China
6    South Africa
7       Indonesia
Name: country, dtype: object

In [2]:
# Read the csv file into a pandas DataFrame
emission_goals = pd.read_csv('clean_data/nonrenewable_energy.csv')
emission_goals

,country,1965.0,1966.0,1967.0,1968.0,1969.0,1970.0,1971.0,1972.0,1973.0,...,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0
0,Canada,4.924317,5.239095,5.480214,5.836056,6.185953,6.624581,6.831992,7.348642,7.857612,...,12.790267,13.354323,13.189590,13.590863,13.728664,13.555908,13.448364,13.617474,13.846043,13.690659
1,Mexico,1.050253,1.111572,1.132470,1.232997,1.353689,1.444834,1.519984,1.680466,1.811085,...,7.222912,7.571642,7.603508,7.626757,7.563910,7.531233,7.614967,7.711194,7.616859,7.375450
2,US,52.300473,55.242418,57.171040,60.643634,63.887342,66.053149,67.426099,70.877600,73.784978,...,90.215943,88.997395,86.362665,88.339194,89.014878,87.900180,87.210132,87.091241,90.098983,88.820249
3,Total North America,58.275043,61.593084,63.783724,67.712687,71.426984,74.122564,75.778076,79.906708,83.453675,...,110.229121,109.923361,107.155763,109.556815,110.307452,108.987321,108.273463,108.419909,111.561886,109.886358
4,Argentina,1.127632,1.165108,1.199725,1.241234,1.283912,1.212287,1.287880,1.310799,1.367420,...,3.186537,3.236700,3.317457,3.454196,3.429151,3.503187,3.494517,3.472192,3.440353,3.323775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,Total Asia Pacific,18.602918,20.276199,21.238757,22.889208,26.013779,29.617329,32.439369,34.360105,37.115662,...,194.850335,204.953750,211.174881,217.107857,220.940343,223.779504,227.172042,232.533550,240.065790,246.745800
99,Total World,155.476758,163.864141,170.038973,180.389356,192.587734,204.708413,213.034394,224.585136,237.515569,...,496.324801,507.190181,512.377182,520.547704,523.222440,525.093831,530.544258,537.385046,550.402897,554.922514
100,of which: OECD,109.574113,115.011533,119.557890,127.542597,136.081359,143.559737,147.442299,154.999355,163.640237,...,225.915701,222.477271,219.029291,220.139552,217.369543,216.567934,216.682393,217.515120,220.116760,216.663061
101,Non-OECD,45.902645,48.852609,50.481083,52.846759,56.506375,61.148675,65.592095,69.585781,73.875332,...,270.409100,284.712910,293.347892,300.408152,305.852897,308.525897,313.861865,319.869926,330.286138,338.259454
102,European Union #,42.064094,43.242832,44.466328,47.343083,50.875159,54.125978,55.394062,58.050755,61.300808,...,70.775945,67.708374,66.428302,65.426367,62.328984,62.494851,63.085514,63.217839,62.837211,61.264978